finetuner:
- optim:
    batch_size: 1
    break_below_lr: 1.0e-07
    checkpoint_every: 100000
    eps: 1.0e-08
    eval_every: 1
    factor: 0.9
    force_coefficient: 100
    lr_initial: 0.0003
    max_epochs: 400
    num_workers: 0
    optimizer_params:
      eps: 1.0e-08
      weight_decay: 0
    patience: 3
    # print_loss_and_lr: true
    scheduler_loss: train
    weight_decay: 0
  task:
    primary_metric: loss
  tuner:
    num_threads: 8
    unfreeze_blocks:
    - out_blocks.3.seq_forces
    - out_blocks.3.scale_rbf_F
    - out_blocks.3.dense_rbf_F
    - out_blocks.3.out_forces
    - out_blocks.2.seq_forces
    - out_blocks.2.scale_rbf_F
    - out_blocks.2.dense_rbf_F
    - out_blocks.2.out_forces
    - out_blocks.1.seq_forces
    - out_blocks.1.scale_rbf_F
    - out_blocks.1.dense_rbf_F
    - out_blocks.1.out_forces
learner:
  dyn_avg_steps: 15
  dyn_uncertain_tol: 1000000 # Dynamic uncertainty tolerance
  # fmax_verify_threshold: 0.03 # Fmax threshold for calling VASP single point calculation
  # initial_points_to_keep: []
  logger:
    pca_quantify: true # Log PCA on wandb
    uncertainty_quantify: false
  num_initial_points: 1  # Number of VASP calls at the beginning of the relaxation
  partial_fit: true
  query_every_n_steps: 30 # K-steps querying strategy: query every 100 steps
  stat_uncertain_tol: 1000000 # Static uncertainty tolerance
  tolerance_selection: min
  # valset_system_id: '1498818'
  wandb_init:
    entity: ulissi-group
    project: project
    group: group
    name: name
    notes: notes
    wandb_log: false # Wandb disabled
# optional_config:
#   links:
#     traj: /path/to/vasp/reference/traj
ocp:
  model_class_list:
  - gemnet
  checkpoint_path_list:
  - /home/jovyan/shared-scratch/joe/optim_cleaned_checkpoints/gemnet_s2re_bagging_results/gem_homo_run0.pt
relaxation:
  # fmax: 0.03
  max_parent_calls: null
  maxstep: 0.2
  replay_method: parent_only
  steps: null
  trajname: oal_relaxation.traj
